# Generated by Django 4.2.7 on 2023-12-16 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_mobile_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='cancelledTransactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MerchantRequestID', models.CharField(max_length=255)),
                ('CheckoutRequestID', models.CharField(max_length=255)),
                ('ResultDesc', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='succesfulTransactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MerchantRequestID', models.CharField(max_length=255)),
                ('CheckoutRequestID', models.CharField(max_length=255)),
                ('ResultDesc', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('MpesaReceiptNumber', models.CharField(max_length=255)),
                ('transactionDate', models.DateTimeField(auto_now_add=True)),
                ('phone', models.CharField(max_length=30)),
            ],
        ),
    ]
