# Generated by Django 4.2.7 on 2023-12-17 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_cancelledtransactions_succesfultransactions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cancelledtransactions',
            old_name='ResultDesc',
            new_name='ResultCode',
        ),
        migrations.RenameField(
            model_name='succesfultransactions',
            old_name='amount',
            new_name='Amount',
        ),
        migrations.RenameField(
            model_name='succesfultransactions',
            old_name='phone',
            new_name='PhoneNumber',
        ),
        migrations.RenameField(
            model_name='succesfultransactions',
            old_name='transactionDate',
            new_name='TransactionDate',
        ),
    ]
