# Generated by Django 4.2.7 on 2023-12-17 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_rename_resultdesc_cancelledtransactions_resultcode_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallbackData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant_request_id', models.CharField(max_length=255)),
                ('checkout_request_id', models.CharField(max_length=255)),
                ('result_code', models.IntegerField()),
                ('result_desc', models.CharField(max_length=255)),
                ('amount', models.FloatField(null=True)),
                ('mpesa_receipt_number', models.CharField(max_length=255, null=True)),
                ('balance', models.FloatField(null=True)),
                ('transaction_date', models.DateTimeField(null=True)),
                ('phone_number', models.CharField(max_length=15, null=True)),
            ],
        ),
    ]
