# Generated by Django 4.2.7 on 2023-12-20 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_businesstocustomer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesstocustomer',
            name='Amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='businesstocustomer',
            name='MpesaReceiptNumber',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='businesstocustomer',
            name='PhoneNumber',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='businesstocustomer',
            name='TransactionDate',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
