# Generated by Django 4.2.7 on 2023-12-22 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_alter_businesstocustomer_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MerchantRequestID', models.CharField(max_length=255)),
                ('CheckoutRequestID', models.CharField(max_length=255)),
                ('ResultDesc', models.CharField(max_length=255)),
                ('Amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('MpesaReceiptNumber', models.CharField(max_length=255)),
                ('TransactionDate', models.DateTimeField(auto_now_add=True)),
                ('PhoneNumber', models.CharField(max_length=30)),
            ],
        ),
    ]
