"""
Django settings for crypto2fiat project.

Generated by 'django-admin startproject' using Django 4.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-_7t3^f#n%tvk@+-s99wrcumpa-a9p32)9r_whrgvu3^^_pp1u5'

# SECURITY WARNING: don't run with debug turned on in production!


ALLOWED_HOSTS = ["gm0ojpbh6f.execute-api.eu-west-1.amazonaws.com","*"]

DEBUG = True
# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'payments',
    'rest_framework',
    'corsheaders',
    'whitenoise.runserver_nostatic', 

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
]

ROOT_URLCONF = 'crypto2fiat.urls'
CORS_ALLOW_ALL_ORIGINS = True

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'crypto2fiat.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases
# __import__('pysqlite3')
# import sys
# sys.modules['sqlite3'] = sys.modules.pop('pysqlite3')

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
       
#     }
# }


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'GMT'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_STORAGE="whitenoise.storage.CompressedManifestStaticFilesStorage"

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
# SMTP CONFIGURATIONS
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = config('EMAIL_HOST')
# EMAIL_HOST_USER = config('EMAIL_HOST_USER')
# DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL')
# SERVER_EMAIL = config('SERVER_EMAIL')
# EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD')


SAFARICOM_AUTH_ENDPOINT=config('SAFARICOM_AUTH_ENDPOINT')
SAFARICOM_AUTH_KEY=config('SAFARICOM_AUTH_KEY')
SAFARICOM_AUTH_CONSUMER_SECRET=config('SAFARICOM_AUTH_CONSUMER_SECRET')
SAFARICOM_STK_PUSH=config('SAFARICOM_STK_PUSH')
SAFARICOM_PASS_KEY=config('SAFARICOM_PASS_KEY')
BUSINESS_SHORT_CODE=config('BUSINESS_SHORT_CODE')
SAFARICOM_CALLBACK_URL = config('SAFARICOM_CALLBACK_URL')
SAFARICOM_TIMEOUT_URL = config('SAFARICOM_TIMEOUT_URL')
SAFARICOM_SECURITY_CREDENTIAL_B2C = config('SAFARICOM_SECURITY_CREDENTIAL_B2C')
# *************b2c credentials****************
INITIATOR_NAME = config('INITIATOR_NAME')
SECURITY_CREDENTIAL = config('SECURITY_CREDENTIAL')
COMMANDID = config('COMMANDID')
SAFARICOM_B2C_ENDPOINT = config('SAFARICOM_B2C_ENDPOINT')
SANDBOX_CERTIFICATE= config('SANDBOX_CERTIFICATE')
INITIATOR_PASSWORD = config('INITIATOR_PASSWORD')
# *********Africa's talking credentials*********
AFRICAS_TALKING_USERNAME = config('AFRICAS_TALKING_USERNAME')
AFRICAS_TALKING_API_KEY = config('AFRICAS_TALKING_API_KEY')

SMS_KEY = config('SMS_KEY')
SMS_USERNAME = config('SMS_USERNAME')


STRIPE_SECRET_KEY=config('STRIPE_SECRET_KEY')
SUCCESS_URL=config('SUCCESS_URL')
CANCEL_URL=config('CANCEL_URL')
